export const freetimerStores = {
  play: "https://play.google.com/store/apps/details?id=com.jacobsfactory.freetimer.android",
  windows: "https://apps.microsoft.com/detail/9NCR1DNFJCP6",
} as const;

export const freetimerCopy = {
  ko: {
    tagline: "탭 한 번에 집중. 광고 없음.",
    intro: [
      "FreeTimer는 집중할 일을 버튼으로 만들어 두고, 탭 한 번에 타이머를 시작하는 앱입니다.",
      "하고 싶은 일을 이름과 시간만 정해 두면 됩니다. 수학 50분, 영어 25분처럼 자주 쓰는 집중을 홈 화면에 바로 꺼내 둘 수 있습니다. 그룹으로 나누고, 완료 횟수와 기록을 주·월·연 단위로 볼 수 있습니다.",
      "타이머를 켜 둔 동안 비, 숲, 카페 같은 집중 소리를 틀 수 있습니다. 추가 소리는 필요할 때 받습니다. 홈 화면에는 오늘의 한 줄을 띄울 수 있습니다.",
      "Google 계정으로 한 번 연결하면 이 PC와 Android 앱의 작업·기록이 맞춰집니다. 로그인은 선택이며, 켜면 이 앱 전용 Google Drive 숨은 폴더에만 동기화됩니다. 광고가 없고, 핵심 기능은 모두 무료입니다.",
    ],
    featuresTitle: "기능",
    features: [
      "탭 한 번에 시작하는 작업별 타이머",
      "그룹으로 작업 정리",
      "주·월·연 기록과 통계",
      "비, 숲, 카페 등 집중 소리",
      "홈 화면의 오늘의 한 줄",
      "라이트·다크·컬러 스킨",
      "기기 백업과 자동 백업",
      "선택 Google 동기화 (PC와 Android)",
    ],
    screenshotsTitle: "화면",
    screenshots: [
      { src: "/apps/freetimer/home.png", alt: "홈 화면의 작업 버튼" },
      { src: "/apps/freetimer/timer.png", alt: "실행 중인 타이머" },
      { src: "/apps/freetimer/stats.png", alt: "주간 통계" },
      { src: "/apps/freetimer/history.png", alt: "완료 기록" },
    ],
    getTitle: "받기",
    play: "Google Play",
    windows: "Microsoft Store",
    ios: "App Store",
    iosSoon: "준비 중",
    privacy: "개인정보처리방침",
    terms: "이용약관",
    back: "Jacobs Factory",
    contact: "문의",
  },
  en: {
    tagline: "One-tap focus timer. No ads.",
    intro: [
      "FreeTimer turns the things you want to focus on into buttons. Tap one, and the timer starts.",
      "Give a task a name and a duration — 50 minutes of math, 25 minutes of writing — and keep it on the home screen. Organize tasks into groups, then review completed sessions by week, month, or year.",
      "Play rain, forest, cafe, or other focus sounds while the timer runs. Extra sounds download when you need them. A short quote of the day can appear on the home screen.",
      "Sign in with Google once and this PC stays in sync with your other devices, including the Android app. Sign-in is optional. If you turn it on, data syncs only to this app’s hidden Google Drive folder. There are no ads. Everything you need is free.",
    ],
    featuresTitle: "Features",
    features: [
      "One-tap timers for each task",
      "Groups to keep work organized",
      "History and stats by week, month, or year",
      "Focus sounds (rain, forest, cafe, and more)",
      "Today’s quote on the home screen",
      "Light, dark, and color skins",
      "Local backup and auto-backup",
      "Optional Google sync across this PC and Android",
    ],
    screenshotsTitle: "Screenshots",
    screenshots: [
      { src: "/apps/freetimer/home.png", alt: "Home screen with task buttons" },
      { src: "/apps/freetimer/timer.png", alt: "Running timer" },
      { src: "/apps/freetimer/stats.png", alt: "Weekly stats" },
      { src: "/apps/freetimer/history.png", alt: "Session history" },
    ],
    getTitle: "Get the app",
    play: "Google Play",
    windows: "Microsoft Store",
    ios: "App Store",
    iosSoon: "Coming soon",
    privacy: "Privacy",
    terms: "Terms",
    back: "Jacobs Factory",
    contact: "Contact",
  },
} as const;
