export const myHealthDiaryStores = {
  play: "https://play.google.com/store/apps/details?id=com.jacobsfactory.myhealthdiary.android",
} as const;

export const myHealthDiaryCopy = {
  ko: {
    name: "내 건강 일기",
    tagline: "병원 가기 전, 말한 것을 한 장으로.",
    intro: [
      "내 건강 일기는 병원 가기 전, 하루하루 달라지는 증상을 날짜별로 남겨 두는 앱입니다.",
      "오늘 아픈 곳을 말하거나 타이핑해 남깁니다. 날짜별·증상별로 모아 보고, 병원 예약과 진료 후기를 같은 앱에 둡니다. 가져갈 기록은 한 장으로 만들 수 있습니다.",
      "계정은 없습니다. 광고도 없습니다. 기록은 이 휴대폰에 둡니다. 말하기를 쓰면 기기의 음성 인식을 씁니다. AI 정리는 버튼을 눌렀을 때만, 그날 글을 칸 초안으로 정리합니다.",
      "환자 기록 요약이며, 진단이나 치료가 아닙니다.",
    ],
    featuresTitle: "기능",
    features: [
      "오늘 증상을 말하거나 타이핑해 남기기",
      "날짜별·증상별로 모아 보기",
      "병원 예약과 진료 후기",
      "가져갈 한 장 기록",
      "선택 잠금 (PIN·생체인식)",
      "계정·광고 없음. 기록은 휴대폰에",
    ],
    screenshotsTitle: "화면",
    screenshots: [
      { src: "/apps/my-health-diary/today.png?v=2", alt: "오늘 화면의 증상과 병원 예약" },
      { src: "/apps/my-health-diary/records.png?v=2", alt: "날짜별 기록" },
      { src: "/apps/my-health-diary/diary.png?v=2", alt: "무릎 일기" },
      { src: "/apps/my-health-diary/hospital.png?v=2", alt: "병원 예약" },
    ],
    getTitle: "받기",
    play: "Google Play",
    ios: "App Store",
    iosSoon: "준비 중",
    privacy: "개인정보처리방침",
    terms: "이용약관",
    back: "Jacobs Factory",
    contact: "문의",
  },
  en: {
    name: "My Health Diary",
    tagline: "Notes for the clinic, on this phone.",
    intro: [
      "My Health Diary is for the days before a clinic visit. You keep a dated record of how symptoms change.",
      "Speak or type what hurts today. Browse by day or by symptom. Keep clinic reservations and after-visit notes in the same app. Make one page to take with you.",
      "There is no account and no ads. Notes stay on this phone. Speak uses the device recognizer. AI organize runs only when you tap it, and drafts that day’s text into fields.",
      "A patient-record summary. Not a diagnosis or a treatment.",
    ],
    featuresTitle: "Features",
    features: [
      "Speak or type today’s symptoms",
      "Browse by day or by symptom",
      "Clinic reservations and after-visit notes",
      "One page to take with you",
      "Optional lock (PIN or biometrics)",
      "No account, no ads. Notes stay on the phone",
    ],
    screenshotsTitle: "Screenshots",
    screenshots: [
      { src: "/apps/my-health-diary/today.png?v=2", alt: "Today with symptoms and a clinic visit" },
      { src: "/apps/my-health-diary/records.png?v=2", alt: "Notes by date" },
      { src: "/apps/my-health-diary/diary.png?v=2", alt: "Knee diary" },
      { src: "/apps/my-health-diary/hospital.png?v=2", alt: "Clinic reservation" },
    ],
    getTitle: "Get the app",
    play: "Google Play",
    ios: "App Store",
    iosSoon: "Coming soon",
    privacy: "Privacy",
    terms: "Terms",
    back: "Jacobs Factory",
    contact: "Contact",
  },
} as const;
