export const sayNoteStores = {
  play: "https://play.google.com/store/apps/details?id=com.jacobsfactory.saynote.android",
} as const;

export const sayNoteCopy = {
  ko: {
    name: "SayNote",
    tagline: "말하면 바로 글로 남는 노트.",
    intro: [
      "SayNote는 말한 것을 노트로 남기는 앱입니다. 첫 화면에서 바로 말하면 됩니다. 마지막 노트는 그 아래에 있어요.",
      "말하면 글자로 저장됩니다. 녹음 파일은 남기지 않습니다. 목록, 달력, 검색, 중요 표시로 다시 찾고, 알림을 맞추거나 읽어주거나 사진을 붙일 수 있습니다. 인식이 안 되면 직접 쓸 수 있습니다.",
      "계정은 없습니다. 광고도 없습니다. 노트는 이 휴대폰에 둡니다. 백업을 보내거나 가져올 수 있고, 기기 안에 자동 백업을 남깁니다.",
      "음성 인식은 기기와 언어에 따라 인터넷이 필요할 수 있습니다. 노트는 당신의 폰에만 있습니다.",
    ],
    featuresTitle: "기능",
    features: [
      "말하면 글자로 남는 노트",
      "목록, 달력, 검색, 중요 표시",
      "로컬 알림과 읽어주기",
      "노트에 사진 붙이기",
      "홈 화면 위젯으로 바로 말하기",
      "테마와 글자 크기",
      "보내기·가져오기 백업, 기기 안 자동 백업",
      "계정·광고 없음. 노트는 휴대폰에",
    ],
    screenshotsTitle: "화면",
    screenshots: [
      { src: "/apps/saynote/home.png", alt: "홈 화면의 말하기 버튼과 최근 노트" },
      { src: "/apps/saynote/speaking.png", alt: "말하는 중 실시간 텍스트" },
      { src: "/apps/saynote/list.png", alt: "노트 목록" },
      { src: "/apps/saynote/calendar.png", alt: "달력과 예정 노트" },
    ],
    getTitle: "받기",
    play: "Google Play",
    ios: "App Store",
    iosSoon: "준비 중",
    privacy: "개인정보처리방침",
    terms: "이용약관",
    back: "Jacobs Factory",
    contact: "문의",
  },
  en: {
    name: "SayNote",
    tagline: "Speak and it becomes a note.",
    intro: [
      "SayNote turns what you say into a note. Open the app and speak. Your last note sits below.",
      "Speech is saved as text. No recording file is kept. Find notes again with the list, calendar, search, and important flag. Set a reminder, listen with read-aloud, or attach a photo. If nothing is recognized, you can write instead.",
      "There is no account and no ads. Notes stay on this phone. Send or import a backup. The app also keeps an automatic backup on the device.",
      "Internet may be needed for speech recognition. Notes stay on your phone.",
    ],
    featuresTitle: "Features",
    features: [
      "Speak and save a note as text",
      "List, calendar, search, and important flag",
      "Local reminders and read-aloud",
      "Photos on a note",
      "Home-screen widget to start speaking",
      "Theme and text size",
      "Export, import, and on-device auto-backup",
      "No account, no ads. Notes stay on the phone",
    ],
    screenshotsTitle: "Screenshots",
    screenshots: [
      { src: "/apps/saynote/home.png", alt: "Home with the speak button and a recent note" },
      { src: "/apps/saynote/speaking.png", alt: "Live text while speaking" },
      { src: "/apps/saynote/list.png", alt: "Notes list" },
      { src: "/apps/saynote/calendar.png", alt: "Calendar with planned notes" },
    ],
    getTitle: "Get the app",
    play: "Google Play",
    ios: "App Store",
    iosSoon: "Coming soon",
    privacy: "Privacy",
    terms: "Terms",
    back: "Jacobs Factory",
    contact: "Contact",
  },
} as const;
